// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef window_h
#define window_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Int_Input.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Button.H>
#include <Fl/Fl_PNG_Image.H>
#include <Fl/Fl_Image.H>

class UserInterface {
public:
  UserInterface();
protected:
  Fl_Box *boxImg;
  Fl_PNG_Image* myimage;
  Fl_Double_Window *w;
  Fl_Int_Input *inputValue1;
  Fl_Box *boxResult;
  Fl_Button *btnSorteio;
  Fl_Button *btnReset;
  Fl_Box *boxGanhador;
};
#endif
